# Generated by Django 3.0 on 2019-07-26 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=600)),
                ('html', models.TextField(blank=True, max_length=2000, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('img1', models.ImageField(upload_to='images/stuff')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='images/stuff')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='images/stuff')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='images/stuff')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.Category', verbose_name='Category')),
            ],
        ),
    ]
